services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./config/mosquitto:/mosquitto/config:ro

  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    ports:
      - "5341:80"
    volumes:
      - seq-data:/data

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      # Mount whole directory containing prometheus.yml
      - ./config/prometheus:/etc/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      # Provision datasources from Git repo
      - ./config/grafana:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=signals
      - POSTGRES_USER=signals
      - POSTGRES_PASSWORD=signals
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U signals -d signals"]
      interval: 5s
      timeout: 3s
      retries: 10

  signals:
    build:
      context: ./src
      dockerfile: ./SDHome.Api/Dockerfile
    container_name: signals
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      mosquitto:
        condition: service_started
      seq:
        condition: service_started
      prometheus:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      
      Signals__Mqtt__Host: mosquitto
      Signals__Mqtt__Port: "1883"

      Signals__Postgres__ConnectionString: "Host=postgres;Port=5432;Database=signals;Username=signals;Password=signals"

      Signals__Webhooks__Main: "http://n8n:5678/webhook/signals/event"
      Signals__Webhooks__Test: "http://n8n:5678/webhook-test/signals/event"

      Logging__SeqUrl: "http://seq"

    ports:
      - "8090:8080"
 
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: zigbee2mqtt
    profiles: ["zigbee"]
    volumes:
      - .config/zigbee:/app/data
    environment:
      - TZ=Europe/London
    devices:
      - /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_d8aa044869afed11b90d394e71c9e8b5-if00-port0:/dev/ttyUSB0
    depends_on:
      - mosquitto
    ports:
      - "8080:8080"

  n8n:
    image: n8nio/n8n:stable
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"   # optional once proxy works
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_SECURE_COOKIE=false
      - GENERIC_TIMEZONE=Europe/London
      - N8N_PATH=/n8n/
      # optional but nice when accessed via domain:
      # - N8N_EDITOR_BASE_URL=https://mydomain.com/n8n/
      # - N8N_DIAGNOSTICS_ENABLED=false
    volumes:
      - n8n_data:/home/node/.n8n

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"       # add 443 later for HTTPS
    depends_on:
      - n8n
      - zigbee2mqtt
      - seq
      - grafana
      - prometheus
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d:ro

volumes:
  seq-data:
  grafana-data:
  postgres-data:
  n8n_data:
